# Generated by Django 5.2 on 2025-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_banneduserhistory_reject_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='unread', max_length=20),
        ),
    ]
